export const nameMap = {
  "/": "Login",
  "/register": "Register",
  "/lupaPassword": "Lupa Password",
  "/dashboard": "Dashbord",
  "/manageAssetImage": "Manage Asset Image",
  "/manageAssetImage/add": "Add New Image",
  "/manageAssetVideo": "Manage Asset Video",
  "/manageAssetVideo/add": "Add New Video",
  "/manageAssetDataset": "Manage Asset Dataset",
  "/manageAssetDataset/add": "Add New Dataset",
  "/manageAsset2D": "Manage Asset 2D",
  "/manageAsset3D": "Manage Asset 3D",
  "/manageAssetAudio": "Manage Asset Audio",
  "/manageAdmin": "Manage Admin",
  "/manageAdmin/add": "Add New Admin",
  // "/manageAdmin/edit/:id": "Edit Admin", // nnati kita edit nembak id data nya
  "/manageAdmin/edit": "Edit Admin",
  "/landingPage": "Landing Page",
  "*": "Error Page 404",
};
