export const nameMap = {
  "/": "Login",
  "/register": "Register",
  "/lupaPassword": "Lupa Password",
  "/dashboard": "Dashbord",
  "/sale": "Sales",
  "/revenue": "Revenue",
  "/landingPage": "Landing Page",
  "/manageAssetVideo": "Manage Asset Video",
  "/manageAssetVideo/add": "Add New Video",
  "/manageAssetVideo/edit": "Edit Video",
  "/manageAssetImage": "Manage Asset Image",
  "/manageAssetImage/add": "Add New Image",
  "/manageAssetImage/edit/:id": "Edit Image",
  "/manageAssetDataset": "Manage Asset Dataset",
  "/manageAssetDataset/add": "Add New Dataset",
  "/manageAssetDataset/edit/:id": "Edit Dataset",
  "/manageAsset2D": "Manage Asset 2D",
  "/manageAsset2D/add": "Add New Asset 2D",
  "/manageAsset2D/edit": "Edit Asset 2D",
  "/manageAsset3D": "Manage Asset 3D",
  "/manageAsset3D/add": "Add New Asset 3D",
  "/manageAsset3D/edit": "Edit Asset 3D",
  "/manageAssetAudio": "Manage Asset Audio",
  "/manageAssetAudio/add": "Add New Audio",
  "/manageAssetAudio/edit/:id": "Edit Audio",
  "/manageAdmin": "Manage Admin",
  "/manageAdmin/add": "Add New Admin",
  "/manageAdmin/edit/:id": "Edit Admin",
  "/manageUsers": "Manage Users",
  "/manageUsers/add": "Add New User",
  "/manageUsers/edit/:id": "Edit User",
  "*": "Error Page 404",
};
